[package]
name = "space-game"
version = "0.1.0"
authors = ["Bjørn Uhre Arnholtz <rugkiks@gmail.com>"]
repository = "https://github.com/bjornua/space-game"
license = "MIT"
readme = "README.md"

[profile.dev]
debug = true
